url: https://tyolab.github.io
baseurl: /web/

# Site settings
title: TYO Lab
email: support@tyo.com.au
description: "We are dedicated to providing advanced online technology to make life easier." 

links:
  - name:         About
    url:          /about
  - name:         Blog
    url:          http://www.tyo.com.au/blog
    external:     true
  - name:         Email
    url:          mailto:support@tyo.com.au
    external:     true
  - name:         GitHub
    url:          http://github.com/tyolab
    external:     true
highlighter:      pygments
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
