url: "https://tyolab.github.io"
#url: "http://localhost:4000"
baseurl: "/web"

# Site settings
title: TYO Lab
email: support@tyo.com.au
description: "Dedication to providing advanced online technologies that make life easy."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: TYO Lab

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/tyolab
  - title: github
    url: https://github.com/tyolab

# Build settings
markdown: kramdown
permalink: pretty
